# Generated by Django 6.0.3 on 2026-03-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_actor_birth_year_remove_director_birth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
