# Generated by Django 6.0.3 on 2026-05-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movie_plot_summary_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
